server:
  port: 9090
spring:
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  datasource:
    name: bigZ
    username: su
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bigZ